### ISSUE TITLE
Rosrun

### ISSUE THREAD

**Issue by DrUlysses** [robocup-logistics/gazebo-rcll#16]
Hello, I'm trying to run gazebo as ros node (rosrun gazebo_ros gazebo), but my Insert tab has no models, only the paths to models are shown there. When I'm running gazebo alone, not as ros node - I can see models in Insert tab.

**Comment by zwilling** [comment]
Hi DrUlysses,
Gazebo uses some environmental variables to figure out which models can be inserted. You can find our setup in the Readme.
Could it be that your ROS environment overrides these environmental variables?

**Comment by DrUlysses** [comment]
So I have set your variables in bashrc and in gazebo/setup.sh. 
How can I check, if ROS overrides the variables? Must I go through the gazebo_ros code or?

**Comment by DrUlysses** [comment]
So I have tried to run gazebo on the fresh virtual machine, but I became the same problem. I have set the variables in bashrc and in the share/gazebo/setup.sh as well.
![image](https://user-images.githubusercontent.com/8532343/40969365-fba59cee-68b7-11e8-8897-077e956dd330.png)
