### ISSUE TITLE
Simulation crashes if RS is prepared without a workpiece

### ISSUE THREAD

**Issue by morxa** [robocup-logistics/gazebo-rcll#18]
Preparing an RS without putting a workpiece on its input crashes/freezes the simulation. The reason is that the MPS plugin tries to move the workpiece from the input to the output, but there is no workpiece.

This has been observed with the RS, but may also occur for other MPS types.

**Comment by MostafaGomaa** [comment]
fixed by #20

**Comment by MostafaGomaa** [comment]
fixed by #20

**Comment by MostafaGomaa** [comment]
fixed by #20
