### ISSUE TITLE
Supported gazebo versions

### ISSUE THREAD

**Issue by pkohout** [robocup-logistics/gazebo-rcll#21]
Hi,
Is only Gazebo 7.0 working, I have not found any information about that? Are there any plans to update the plugins to support a newer version?

Thanks a lot,
Peter

**Comment by pkohout** [comment]
Ok I just forgot recompile the tag library :D so 7.16 is working, my fault. 
But it would be still nice to know what version you are aware that a working (8, 9, 10, 11).

**Comment by morxa** [comment]
We're currently using Gazebo 9.5 and we have been using Gazebo 8 before, so those definitely work.
