### ISSUE TITLE
[Question] Plugin initialisation in constructor instead of Load method

### ISSUE THREAD

**Issue by ValentinVERGEZ** [robocup-logistics/gazebo-rcll#4]
Hi @zwilling,

I'm wondering why in mps plugin (mps.cpp specifically) all the initialization stuff is done in class constructor instead of Load() method like on many others plugins and like recommended by gazebosim. 

Is there any technical reason, or could the initialization be moved safely ? 

Thanks

**Comment by zwilling** [comment]
Hi @ValentinVERGEZ 
your right, the initialization stuff usually belongs into the Load function.
I don't see technical reasons against moving it. But when you move it, make sure to call the Load of the Superclass (Mps) in the Subclasses (CapStation, ...)
Kind Regards

**Comment by ValentinVERGEZ** [comment]
Yes indeed.
Thanks for the quick answer.

Regards.
