### ISSUE TITLE
error: redefinition of ‘struct spdlog::details::null_mutex’  struct null_mutex

### ISSUE THREAD

**Issue by hg-tc** [robocup-logistics/gazebo-rcll#56]
error: redefinition of ‘struct spdlog::details::null_mutex’
 struct null_mutex

I met the problem when cmake build:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/57742058/185281984-8ba8920f-0219-404a-a2d8-773d8cf5ca9e.png">

can anyone help me?

**Comment by pkohout** [comment]
Hi, we always build gazebo-rcll with a system installation of spdlog which works fine. I am not sure what version is downloaded via FetchAndDeclare, but I will try it out on my PC later and check if there is some sort of bug there, since I never use it.

**Comment by morxa** [comment]
The problem is that freeopcua ships with its own copy of spdlog, which then clashes with the target imported via FetchContent.

As @pkohout said, if you install spdlog on your system, both freeopcua and gazebo-rcll will include the system version, which should fix the issue.
