### ISSUE TITLE
cannot find /opc/ua/client/client.h

### ISSUE THREAD

**Issue by hg-tc** [robocup-logistics/gazebo-rcll#57]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/57742058/185283168-000fb025-8479-4499-8319-95458c086358.png">
the info shows that 

but i did install the third_patry

**Comment by pkohout** [comment]
As far as I know there is no apt package for freeopcua, I guess you installed it by source, can you let me know which version you used? We install the following commit: `https://github.com/FreeOpcUa/freeopcua/tree/bd13aee2455c1d137bee45f7d2aedea8dd30115c` which works fine for us.

**Comment by morxa** [comment]
This is an issue with the include directories of freeopcua, see FreeOpcUa/freeopcua#394.

**Comment by hg-tc** [comment]
This problem is effectively solved by setting the include directory for BUILD_INTERFACE before freeopcua cmake, but it is better to install spdlog and freeopcua yourself before rcll cmake

**Comment by Unknown-Student** [comment]
Hello,
I have the same issue but could not get it to work with the suggested fixes.

Here is what I did:

1. cloned the freeopcua repo 
2. changed the CMakeList.txt for the one from @morxa 
3. build it
4. clone the gazebo-rcll repo and build it

the progess stops at 86% and the compitaltion is termiated for the same reason as above.

@hg-tc could you tell me what the steps were which you took to make it work

Best Regards
