### ISSUE TITLE
Member request

### ISSUE THREAD

**Issue by ValentinVERGEZ** [robocup-logistics/gazebo-rcll#8]
Hi,

Can I be added to the repo members (even with None rights) please ?
I need this to setup slack integration :stuck_out_tongue:

**Comment by zwilling** [comment]
Hi,
sorry for the delay. I had to finish my thesis.
Tim sent you an invitation.

**Comment by timn** [comment]
Invitation has been issued to join the organization on the developer team. Remember, with power comes responsibility. Please coordinate with your fellow developers on your efforts, for now this is in particular @zwilling for the gazebo-rcll repo.

**Welcome to the RoboCup Logistics Github organization!**

**Comment by ValentinVERGEZ** [comment]
Hi,
I accepted the invitation, thank you @timn !
